# Based on https://github.com/Morton-Li/PyTorch-MacOS-Builder/blob/main/.github/workflows/auto-build-pytorch.yml
name: Build PyTorch

on:
  workflow_dispatch:
  push:

jobs:
  fetch_pytorch:
    name: Fetch PyTorch
    runs-on: macos-15-intel
    steps:
      - name: Check PyTorch cache existence
        id: check-pytorch-cache
        uses: actions/cache/restore@v4
        with:
          path: pytorch
          key: pytorch-v2.8.0
          lookup-only: true

      - name: Clone PyTorch repo
        if: steps.check-pytorch-cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch "v2.8.0" --recursive https://github.com/pytorch/pytorch.git pytorch
          git -C pytorch submodule update --init --recursive --depth 1 || git -C pytorch submodule update --init --recursive --depth 10 || git -C pytorch submodule update --init --recursive

      - name: Save PyTorch source to cache
        id: cache-save
        if: steps.check-pytorch-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: pytorch
          key: pytorch-v2.8.0

  build_libtorch:
    name: Build LibTorch
    needs: [fetch_pytorch]
    runs-on: macos-15-intel
    steps:
      - name: Restore LibTorch ccache Cache
        id: restore-ccache
        uses: actions/cache/restore@v4
        with:
          path: /Users/runner/Library/Caches/ccache
          key: ccache-LibTorch-v2.8.0
          lookup-only: true

      - name: Restore PyTorch source from cache
        id: restore-source-code
        if: steps.restore-ccache.outputs.cache-hit != 'true'
        uses: actions/cache/restore@v4
        with:
          path: pytorch
          key: pytorch-v2.8.0
          fail-on-cache-miss: true

      - name: Build LibTorch
        if: steps.restore-ccache.outputs.cache-hit != 'true'
        env:
          USE_CUDA: "OFF"
          USE_CUDNN: "OFF"
          USE_CUSPARSELT: "OFF"
          USE_MPS: "ON"
          USE_ROCM: "OFF"
          USE_ROCM_KERNEL_ASSERT: "OFF"
          USE_NNPACK: "ON"
          USE_MPI: "OFF"
          USE_DISTRIBUTED: "ON"
          USE_PYTORCH_METAL_EXPORT: "ON"
          BLAS: "MKL"
          USE_MKLDNN: "ON"
          USE_OPENMP: "ON"
          PYTORCH_BUILD_VERSION: "2.8.0"
          PYTORCH_BUILD_NUMBER: "1"
          CMAKE_OSX_ARCHITECTURES: "x86_64"
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          BUILD_TEST: "OFF"
          CC: "/Applications/Xcode_16.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
          CXX: "/Applications/Xcode_16.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++"
          LDSHARED: "clang -bundle -undefined dynamic_lookup"
        run: |
          set -e
          
          brew install ccache
          ccache --version
          ccache -s

          sudo xcode-select --switch /Applications/Xcode_16.4.app

          export MAX_JOBS=$(sysctl -n hw.logicalcpu)
          if [ "$MAX_JOBS" -gt 4 ]; then
              export MAX_JOBS=4
          fi
          
          python3.13 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r pytorch/requirements.txt
          pip install --force-reinstall cmake==3.31.6
          pip install mkl-static==2023.2.2 mkl-include==2023.2.2

          export CMAKE_PREFIX_PATH="$(realpath venv/lib)"
          export CMAKE_INCLUDE_PATH="$(realpath venv/include)"
          
          wget -O /Applications/Xcode_16.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17.0.0/include/omp.h https://github.com/intel/llvm/raw/refs/heads/sycl/openmp/runtime/src/include/omp.h.var

          echo "➡️ Building LibTorch v2.8.0"

          cd pytorch
          git clean -xfd
          
          find scripts -type f -name "*.sh" -exec chmod +x {} +

          export CMAKE_OSX_SYSROOT="$(xcrun --sdk macosx --show-sdk-path)"

          python -m tools.build_libtorch

          ccache -s

      - name: Save LibTorch ccache Cache
        if: steps.restore-ccache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: /Users/runner/Library/Caches/ccache
          key: ccache-LibTorch-v2.8.0

  build_wheel:
    runs-on: macos-15-intel
    needs: [fetch_pytorch, build_libtorch]
    strategy:
      matrix:
        python_version: ['3.12']
    name: Build PyTorch for Python ${{ matrix.python_version }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Restore PyTorch source from cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: pytorch
          key: pytorch-v2.8.0
          fail-on-cache-miss: true

      - name: Restore LibTorch ccache Cache
        uses: actions/cache/restore@v4
        with:
          path: /Users/runner/Library/Caches/ccache
          key: ccache-LibTorch-v2.8.0

      - name: Build wheel
        env:
          USE_CUDA: "OFF"
          USE_CUDNN: "OFF"
          USE_CUSPARSELT: "OFF"
          USE_MPS: "ON"
          USE_ROCM: "OFF"
          USE_ROCM_KERNEL_ASSERT: "OFF"
          USE_NNPACK: "ON"
          USE_MPI: "OFF"
          USE_DISTRIBUTED: "ON"
          USE_PYTORCH_METAL_EXPORT: "ON"
          BLAS: "MKL"
          USE_MKLDNN: "ON"
          USE_OPENMP: "ON"
          PYTORCH_BUILD_VERSION: "2.8.0"
          PYTORCH_BUILD_NUMBER: "1"
          CMAKE_OSX_ARCHITECTURES: "x86_64"
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          BUILD_TEST: "OFF"
          CC: "/Applications/Xcode_16.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
          CXX: "/Applications/Xcode_16.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++"
          LDSHARED: "clang -bundle -undefined dynamic_lookup"
        run: |
          set -e

          brew install ccache
          ccache --version

          sudo xcode-select --switch /Applications/Xcode_16.4.app

          export MAX_JOBS=$(sysctl -n hw.logicalcpu)
          if [ "$MAX_JOBS" -gt 4 ]; then
              export MAX_JOBS=4
          fi

          mkdir -p wheels
          
          python${{ matrix.python_version }} -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r pytorch/requirements.txt
          pip install --force-reinstall cmake==3.31.6
          pip install mkl-static==2023.2.2 mkl-include==2023.2.2

          export CMAKE_PREFIX_PATH="$(realpath venv/lib)"
          export CMAKE_INCLUDE_PATH="$(realpath venv/include)"
          
          wget -O /Applications/Xcode_16.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17.0.0/include/omp.h https://github.com/intel/llvm/raw/refs/heads/sycl/openmp/runtime/src/include/omp.h.var

          echo "➡️ Building PyTorch v2.8.0 with Python ${{ matrix.python_version }}"

          cd pytorch
          git clean -xfd
          
          find scripts -type f -name "*.sh" -exec chmod +x {} +

          export CMAKE_OSX_SYSROOT="$(xcrun --sdk macosx --show-sdk-path)"

          echo "Applying all patches ..."
          find ../patches -type f -name "*.patch" -print | sort | while read -r patch; do
            echo " -> Applying $patch"
            git apply --check "$patch" || { echo "❌ Failed to apply $patch"; exit 1; }
            git apply "$patch"
          done

          python setup.py bdist_wheel --plat-name=macosx_11_0_$CMAKE_OSX_ARCHITECTURES

          ccache -s

          cp dist/*.whl ../wheels/
          cd ..
          
          if [ "$(ls wheels/*.whl 2>/dev/null | wc -l)" -eq 0 ]; then
            echo "❌ No wheel built. Tag will not be created."
            exit 1
          fi

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: torch-2.8.0-py${{ matrix.python_version }}-macosx-wheel
          path: wheels/*.whl

      - name: Test PyTorch wheel
        id: test-wheel
        run: |
          set -e
          python${{ matrix.python_version }} -m venv test-venv
          source test-venv/bin/activate
          pip install --upgrade pip setuptools numpy
          pip install wheels/*.whl

          python -c "import torch; print(f'Torch version: {torch.__version__}'); print(f'Metal Performance Shaders (MPS) support: {torch.backends.mps.is_built()}')"
